baseURL: "https://ilinayozova.github.io"
languageCode: "en-us"
title: "Ilina Yozova"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  favicon: "Y (2).png"
  description: "Ilina Yozova - personal webpage"

  # home
  disable_home: false
  profile_image: "/images/pic11.jpg"
  name: "Ilina Yozova"
  namecolor: 00ad8c
  profession: "Profession"
  github: "https://github.com/ilinayozova/"
  linkedin: "https://www.linkedin.com/in/ilina-yozova-38b6ba169/"
  twitter: "https://twitter.com/iyozova/"
  # instagram: "https://instagram.com/"
  profession: "PhD Student"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Ilina, a PhD student at University College London (UCL) (started in September 2021). My research focuses on Bayesian nonparametric methods for causal inference. My first supervisor is Dr. Ioanna Manolopoulou and my second supervisor is Dr. François-Xavier Briol."
  descripe_l2_person: "I am also a Postgraduate Teaching Assistant at UCL tutoring mainly second and third year courses (please see Teaching Section)."
  skills:
    - name: R
      #percentage: 85
    - name: Python
      #percentage: 70
    #- name: Hugo
      #percentage: 80
    - name: CSS
      #percentage: 10

  # Education
  disable_education: false
  education:
    - company: "PhD"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Statistical Science, University College London"
      startdate: September 2021 
      enddate: present
    - company: "BSc"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Statistics, University College London"
      startdate: Septemver 2018
      enddate: June 2021
      featuredpoints:
        - point: First-Class Honours
        - point: Undergraduate Project title
    - company: "HighSchool"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Mathematics and Computer Science, American College London"
      startdate: September 2015
      enddate: June 2018
      featuredpoints:
        - point: Diploma of Completed Secondary Education


  # Teaching
  disable_teaching: false
  teaching:
    - degree: "STAT0006"
      branch: "Linear Models and the Analysis of Variance"
      university: "UCL - Academic Year 2021-2022"
    - degree: "STAT0007"
      branch: "Introduction to Applied Probability"
      university: "UCL - Academic Year 2021-2022"
    - degree: "STAT00023"
      branch: "Computing for Practical Statistics"
      university: "UCL - Academic Year 2021-2022"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: Whether you have a question or just want to say hi, I'll be happy to get in touch!
  email: "ilina.yozova.18@ucl.ac.uk"

  # Footer
  socialiconfooter: true
  recentposts: false
